# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Tilepack < Formula
  desc "Scrape xyz tiles to an mbtiles file"
  homepage "https://github.com/eknowles/tilepack"
  url "https://github.com/eknowles/tilepack/archive/refs/tags/v1.2.3.tar.gz"
  sha256 "84c500f2f437a3be3bd0096891e31081491a56d53ab2897cdd9c9876637a4878"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "tilepack" => "tilepack"
  end

  test do
    assert_match("tilepack #{version}", shell_output("#{bin}/tilepack --version"))
  end
end
