# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class TilePacker < Formula
  desc "Convert a xyz tile url to a mbtiles file"
  homepage "https://github.com/eknowles/tile-packer"
  url "https://github.com/eknowles/tile-packer/archive/refs/tags/v1.2.1.tar.gz"
  sha256 "20bc20c8c96e9fbe2c70d62bc466c7efe14088ea9b6edcd78c05dda1554d0ba9"

  on_macos do
  end

  on_linux do
  end

  def install
    if Hardware::CPU.arm? && OS.mac?
  bin.install "tile-packer" => "tile-packer"
elsif Hardware::CPU.intel? && OS.mac?
  bin.install "tile-packer" => "tile-packer"
elsif OS.linux?
  bin.install "tile-packer" => "tile-packer"
end
  end

  test do
    assert_match("tile-packer #{version}", shell_output("#{bin}/tile-packer --version"))
  end
end
