# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Tilepack < Formula
  desc "Scrape xyz tiles to an mbtiles file"
  homepage "https://github.com/eknowles/tilepack"
  url "https://github.com/eknowles/tilepack/archive/refs/tags/v1.4.0.tar.gz"
  sha256 "7200f715a3b0a080695bed67e515de5ab1088b50085f320ca1dd783e408bdb13"

  on_macos do
    on_intel do
      url "https://github.com/eknowles/tilepack/releases/download/v1.4.0/tilepack-1.4.0-darwin-amd64.tar.gz"
      sha256 "b56301e33cd3309375e1ca7039d7ffc5a68c67cee28bf9a6854308cfaaa5dd1b"
    end

    on_arm do
      url "https://github.com/eknowles/tilepack/releases/download/v1.4.0/tilepack-1.4.0-darwin-arm64.tar.gz"
      sha256 "48944ed195a598ed2e662007a7e3bbf835ed6bbd5db759c470690e3c3134390f"
    end
  end

  on_linux do
  end

  def install
    bin.install "tilepack" => "tilepack"
  end

  test do
    assert_match("tilepack #{version}", shell_output("#{bin}/tilepack --version"))
  end
end
